version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PW=crudjs      
    ports:
      - 3000:3000
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./:/src/app
      # - /src/app/node_modules

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5433:5432
